"""Generate submit/script.py by inlining fe.py.

The evaluation server only sees script.py, requirements.txt and model/, so the
feature code has to live inside script.py. Keeping a hand-maintained copy is how
you get a silent mismatch -- no error, just quietly wrong predictions -- so the
file is generated from fe.py instead and never edited by hand.

    python build_submit.py       # writes submit/script.py and submit.zip
"""
import os
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
SUBMIT = os.path.join(ROOT, "submit")

HEADER = '''"""Inference script for the evaluation server.

    submit.zip/
      model/model.joblib   trees + feature context + the drift offset
      script.py            this file (generated by work/build_submit.py)
      requirements.txt

The server mounts ./data and ./output. Every row is predicted on its own: each
feature comes from that row plus constants frozen into the artifact at training
time, so no statistic is ever taken across evaluation rows.

DO NOT EDIT -- regenerate with `python work/build_submit.py`.
"""
import os
import time

import joblib
import numpy as np
import pandas as pd

'''

MAIN = '''

DATA_DIR = "./data"
MODEL_PATH = "./model/model.joblib"
OUT_PATH = "./output/submission.csv"


def main():
    t0 = time.time()
    art = joblib.load(MODEL_PATH)
    models, columns, ctx = art["models"], art["columns"], art["ctx"]
    offset = art["logit_offset"]
    print(f"model: {len(models)} trees ensembles, {len(columns)} features, "
          f"logit_offset={offset:+.4f} ({time.time() - t0:.1f}s)", flush=True)

    test = pd.read_csv(os.path.join(DATA_DIR, "test.csv"), encoding="utf-8-sig")
    sub = pd.read_csv(os.path.join(DATA_DIR, "sample_submission.csv"),
                      encoding="utf-8-sig")
    print(f"test={len(test)} submission={len(sub)} ({time.time() - t0:.1f}s)",
          flush=True)

    X = build_features(test, ctx, columns)
    p = np.mean([m.predict_proba(X)[:, 1] for m in models], axis=0)

    # season drift: one constant in logit space, identical for every row
    z = np.log(np.clip(p, EPS, 1 - EPS) / (1 - np.clip(p, EPS, 1 - EPS))) + offset
    p = np.clip(1.0 / (1.0 + np.exp(-z)), EPS, 1 - EPS)
    print(f"predicted mean={p.mean():.4f} min={p.min():.4f} max={p.max():.4f} "
          f"({time.time() - t0:.1f}s)", flush=True)

    pred = pd.Series(p, index=test[ID_COL].to_numpy())
    out = pd.DataFrame({ID_COL: sub[ID_COL]})
    out[TARGET_COL] = out[ID_COL].map(pred)
    missing = int(out[TARGET_COL].isna().sum())
    if missing:
        print(f"warning: {missing} row_id(s) had no prediction -> filled with "
              f"the forecast rate", flush=True)
        out[TARGET_COL] = out[TARGET_COL].fillna(art["target_rate"])

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    out.to_csv(OUT_PATH, index=False, encoding="utf-8")
    print(f"wrote {OUT_PATH} rows={len(out)} (total {time.time() - t0:.1f}s)",
          flush=True)


if __name__ == "__main__":
    main()
'''

REQUIREMENTS = ("# intentionally empty: the evaluation image already ships numpy,\n"
                "# pandas, scikit-learn and joblib. Pinning anything here only adds\n"
                "# a way for the install step to fail.\n")


def main():
    with open(os.path.join(HERE, "fe.py"), encoding="utf-8") as f:
        fe_src = f.read()

    os.makedirs(SUBMIT, exist_ok=True)
    script = os.path.join(SUBMIT, "script.py")
    with open(script, "w", encoding="utf-8") as f:
        f.write(HEADER + fe_src + MAIN)
    with open(os.path.join(SUBMIT, "requirements.txt"), "w", encoding="utf-8") as f:
        f.write(REQUIREMENTS)
    print(f"wrote {script}")

    zip_path = os.path.join(ROOT, "submit.zip")
    names = ["script.py", "requirements.txt", os.path.join("model", "model.joblib")]
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for n in names:
            src = os.path.join(SUBMIT, n)
            if not os.path.exists(src):
                raise SystemExit(f"missing {src} -- run train_v4.py first")
            z.write(src, n.replace(os.sep, "/"))
    print(f"wrote {zip_path} ({os.path.getsize(zip_path) / 1e6:.2f} MB)")
    with zipfile.ZipFile(zip_path) as z:
        print("  contents:", z.namelist())


if __name__ == "__main__":
    main()
