"""Inference script for the evaluation server.

    submit.zip/
      model/model.joblib   trees + feature context + the drift offset
      script.py            this file (generated by work/build_submit.py)
      requirements.txt

The server mounts ./data and ./output. Every row is predicted on its own: each
feature comes from that row plus constants frozen into the artifact at training
time, so no statistic is ever taken across evaluation rows.

DO NOT EDIT -- regenerate with `python work/build_submit.py`.
"""
import os
import time

import joblib
import numpy as np
import pandas as pd

"""Feature engineering -- the single source used by training, holdout and submission.

The context (`ctx`) holds every constant learned from train.csv: league means,
the season-rate trend, and per-entity carry tables. It contains nothing but
floats, lists and numpy arrays, so it pickles cleanly under numpy 1.26 on the
evaluation server and can be rebuilt nowhere else by accident.

Why the carry tables exist
--------------------------
`asof_pitcher_n` is a career pitch counter that runs continuously from 2019 into
the evaluation season -- the sample test.csv confirms it (pitcher 21813 ends
2024 at 3085 pitches in train.csv and shows up at 3465 in test.csv). Subtracting
the pitcher's career totals at the end of the previous season from the row's own
asof_* columns therefore recovers what that pitcher has done *this season so
far*:

    season_n     = asof_n           - career_n_at_end_of_prev_season
    season_succ  = asof_rate*asof_n - career_successes_at_end_of_prev_season

The subtracted numbers are per-entity constants learned from train.csv, so every
evaluation row is still transformed on its own -- no statistic is taken across
test rows, which is what the contest forbids.

This matters because `asof_pitcher_success_rate` is career-cumulative and very
stale: across 2024's 249 regular pitchers it correlates only .19 with how they
actually pitched that season, while the reconstructed season-to-date rate
correlates .97.
"""
import numpy as np
import pandas as pd

ID_COL = "row_id"
TARGET_COL = "control_success"
EPS = 1e-6

# fixed so that a 5-row test.csv can never produce different codes than train
CAT_MAPS = {
    "top_bottom": {"B": 0, "T": 1},
    "game_type": {"F": 0, "R": 1},
    "base_state": {"___": 0, "1__": 1, "_2_": 2, "__3": 3,
                   "12_": 4, "1_3": 5, "_23": 6, "123": 7},
}
CAT_COLS = list(CAT_MAPS)

PIT_RATES = ["success", "reverse", "middle", "ball", "strike"]
MIX_RATES = ["fastball", "breaking", "offspeed"]
BAT_RATES = ["success", "middle"]

K_PIT = 200.0    # shrinkage strength for season-to-date rates
K_BAT = 300.0
K_MIX = 100.0

SEASON_MUL = 10000   # key = entity_id * SEASON_MUL + season

# game_type F (the Futures/second-tier games -- trackman_history.csv shows the
# same split as MIN_* teams) changed definition here: its success rate fell from
# .709 to .473 between 2022 and 2023, by the same amount for every single team.
# That is a measurement change, not a trend, so the old rows need quarantining --
# otherwise the tree averages two different labelling regimes together. Flagging
# them is worth ~+26 on the 2024 holdout, and the flag is 0 for every 2025 row.
F_BREAK_SEASON = 2023


# ------------------------------------------------------------------ carry table
def _season_end(df, key, ncol, rates, prefix, use_label):
    """Cumulative totals at the end of each (entity, season).

    The entity's last row of a season carries asof_* describing everything
    before it, so totals come back with at most one pitch of slack -- exact for
    `success`, where that row's own label is known.
    """
    idx = df.groupby([key, "season"])[ncol].idxmax()
    cols = [key, "season", ncol] + [prefix + r + "_rate" for r in rates]
    if use_label:
        cols = cols + [TARGET_COL]
    last = df.loc[idx, cols]
    n = last[ncol].to_numpy(dtype="float64")
    out = pd.DataFrame({key: last[key].to_numpy(), "season": last["season"].to_numpy(),
                        "n": n + (1.0 if use_label else 0.0)})
    for r in rates:
        v = last[prefix + r + "_rate"].to_numpy(dtype="float64") * n
        if use_label and r == "success":
            v = v + last[TARGET_COL].to_numpy(dtype="float64")
        out[r] = v
    return out


def _build_carry(tbl, key, rates, seasons):
    """(entity, season) -> totals at end of s-1 ('c_') and season s-1 alone ('s_').

    Forward filled, so a pitcher who sat out 2023 still carries their 2022
    totals into 2024 -- which is what the asof counter does too.
    """
    cols = ["n"] + rates
    ents = np.sort(tbl[key].unique())
    mi = pd.MultiIndex.from_product([ents, seasons], names=[key, "season"])
    g = tbl.set_index([key, "season"])[cols].reindex(mi).groupby(level=0).ffill()
    prev1 = g.groupby(level=0).shift(1)
    prev2 = g.groupby(level=0).shift(2)
    vals = np.hstack([prev1.to_numpy(dtype="float64"),
                      prev1.to_numpy(dtype="float64") - prev2.to_numpy(dtype="float64")])
    idx = prev1.index
    keys = (idx.get_level_values(0).to_numpy(dtype="int64") * SEASON_MUL
            + idx.get_level_values(1).to_numpy(dtype="int64"))
    order = np.argsort(keys)
    names = ["c_" + c for c in cols] + ["s_" + c for c in cols]
    return keys[order], vals[order], names


def fit_context(tr):
    """Everything the feature builder needs, learned from the training rows only."""
    seasons = sorted(int(s) for s in tr.season.unique())
    grid = list(range(seasons[0], seasons[-1] + 3))
    rates = tr.groupby("season")[TARGET_COL].mean().loc[seasons].to_numpy(dtype="float64")

    pit = _season_end(tr, "pitcher_id", "asof_pitcher_n", PIT_RATES, "asof_pitcher_", True)
    mix = _season_end(tr, "pitcher_id", "asof_pitcher_pitchmix_n", MIX_RATES,
                      "asof_pitcher_", False)
    bat = _season_end(tr, "batter_id", "asof_batter_n", BAT_RATES, "asof_batter_", False)

    ctx = {
        "priors": {"success": float(tr["asof_pitcher_success_rate"].mean()),
                   "middle": float(tr["asof_pitcher_middle_rate"].mean())},
        "rp": {c: float(tr[c].mean()) for c in tr.columns
               if c.startswith("asof_") and c.endswith("_rate")},
        "seasons": seasons,
        "season_rates": rates,
    }
    for tag, tbl, key, rl in [("pit", pit, "pitcher_id", PIT_RATES),
                              ("mix", mix, "pitcher_id", MIX_RATES),
                              ("bat", bat, "batter_id", BAT_RATES)]:
        k, v, names = _build_carry(tbl, key, rl, grid)
        ctx[tag + "_keys"], ctx[tag + "_vals"], ctx[tag + "_cols"] = k, v, names
    return ctx


def _lookup(ctx, tag, ids, season):
    """Per-row carry values; rows with no history come back as NaN."""
    keys, vals = ctx[tag + "_keys"], ctx[tag + "_vals"]
    q = ids.astype("int64") * SEASON_MUL + season.astype("int64")
    pos = np.clip(np.searchsorted(keys, q), 0, len(keys) - 1)
    hit = keys[pos] == q
    out = vals[pos].copy()
    out[~hit] = np.nan
    return {name: out[:, i] for i, name in enumerate(ctx[tag + "_cols"])}


def _shrunk(num, den, prior, k):
    return (num + k * prior) / (np.maximum(den, 0.0) + k)


# --------------------------------------------------------------------- features
def build_features(df, ctx, columns=None):
    """All derived values come from the row itself plus constants in `ctx`."""
    priors, rp = ctx["priors"], ctx["rp"]
    X = df.drop(columns=[c for c in (ID_COL, TARGET_COL) if c in df.columns]).copy()
    for col, mapping in CAT_MAPS.items():
        # unseen categories stay missing and go down HistGBM's missing branch
        X[col] = X[col].astype(str).map(mapping).astype("float64")

    # --- count ---
    b, s = X["balls_before"], X["strikes_before"]
    X["count_state"] = (b * 3 + s).astype("float64")
    X["count_diff"] = (s - b).astype("float64")
    X["two_strikes"] = (s == 2).astype("float64")
    X["three_balls"] = (b == 3).astype("float64")
    X["full_count"] = ((b == 3) & (s == 2)).astype("float64")
    X["first_pitch"] = ((b == 0) & (s == 0)).astype("float64")
    X["pitcher_ahead"] = (s > b).astype("float64")
    X["must_strike"] = ((b == 3) & (s < 2)).astype("float64")
    X["can_waste"] = ((s == 2) & (b < 2)).astype("float64")

    # --- game situation ---
    X["same_hand"] = (X["pitcher_hand"] == X["batter_hand"]).astype("float64")
    X["risp"] = ((X["runner_on_2b"] == 1) | (X["runner_on_3b"] == 1)).astype("float64")
    X["bases_loaded"] = (X["num_runners_on"] == 3).astype("float64")
    X["close_game"] = (X["score_diff_pitcher_team"].abs() <= 1).astype("float64")
    X["blowout"] = (X["score_diff_pitcher_team"].abs() >= 5).astype("float64")
    X["late_inning"] = (X["inning"] >= 7).astype("float64")
    X["log_li"] = np.log1p(X["li"])

    # --- recent form vs career ---
    base_s = X["asof_pitcher_success_rate"].fillna(priors["success"])
    base_m = X["asof_pitcher_middle_rate"].fillna(priors["middle"])
    for w in (1, 3, 5):
        X[f"form{w}_success"] = X[f"asof_pitcher_prev{w}_game_success_rate"] - base_s
        X[f"form{w}_middle"] = X[f"asof_pitcher_prev{w}_game_middle_rate"] - base_m
    X["form_trend"] = (X["asof_pitcher_prev1_game_success_rate"]
                       - X["asof_pitcher_prev5_game_success_rate"])

    X["f_old_regime"] = ((X["game_type"] == CAT_MAPS["game_type"]["F"])
                         & (X["season"] < F_BREAK_SEASON)).astype("float64")

    season = X["season"].to_numpy()

    # --- pitcher season-to-date ---
    c = _lookup(ctx, "pit", X["pitcher_id"].to_numpy(), season)
    cn = np.nan_to_num(c["c_n"])
    an = X["asof_pitcher_n"].to_numpy(dtype="float64")
    sn = np.maximum(an - cn, 0.0)
    X["career_prev_n"] = cn
    X["season_n"] = sn
    X["is_debut_season"] = (cn <= 0).astype("float64")
    for r in PIT_RATES:
        prior = rp["asof_pitcher_" + r + "_rate"]
        cum = X["asof_pitcher_" + r + "_rate"].to_numpy(dtype="float64") * an
        base = np.nan_to_num(c["c_" + r])
        std = _shrunk(cum - base, sn, prior, K_PIT)
        car = np.where(cn > 0, base / np.maximum(cn, 1.0), np.nan)
        X["std_" + r] = std
        X["career_" + r] = car
        X["std_vs_career_" + r] = std - np.where(np.isnan(car), prior, car)
    for r in ["success", "middle", "ball", "strike"]:
        X["prevseason_" + r] = _shrunk(c["s_" + r], c["s_n"],
                                       rp["asof_pitcher_" + r + "_rate"], K_PIT)
    X["prevseason_n"] = c["s_n"]

    # --- pitch mix season-to-date ---
    cm = _lookup(ctx, "mix", X["pitcher_id"].to_numpy(), season)
    cnm = np.nan_to_num(cm["c_n"])
    anm = X["asof_pitcher_pitchmix_n"].to_numpy(dtype="float64")
    snm = np.maximum(anm - cnm, 0.0)
    for r in MIX_RATES:
        prior = rp["asof_pitcher_" + r + "_rate"]
        cum = X["asof_pitcher_" + r + "_rate"].to_numpy(dtype="float64") * anm
        X["std_" + r] = _shrunk(cum - np.nan_to_num(cm["c_" + r]), snm, prior, K_MIX)

    # --- batter season-to-date ---
    cb = _lookup(ctx, "bat", X["batter_id"].to_numpy(), season)
    cnb = np.nan_to_num(cb["c_n"])
    anb = X["asof_batter_n"].to_numpy(dtype="float64")
    snb = np.maximum(anb - cnb, 0.0)
    X["bat_career_prev_n"] = cnb
    X["bat_season_n"] = snb
    for r in BAT_RATES:
        prior = rp["asof_batter_" + r + "_rate"]
        cum = X["asof_batter_" + r + "_rate"].to_numpy(dtype="float64") * anb
        X["bat_std_" + r] = _shrunk(cum - np.nan_to_num(cb["c_" + r]), snb, prior, K_BAT)
        X["bat_career_" + r] = np.where(cnb > 0, np.nan_to_num(cb["c_" + r])
                                        / np.maximum(cnb, 1.0), np.nan)
        X["bat_prevseason_" + r] = _shrunk(cb["s_" + r], cb["s_n"], prior, K_BAT)

    # std_success and bat_std_success both sit on the current season's league
    # level, so their difference cancels the level out. That is worth having
    # precisely because the level is the one thing we cannot forecast.
    X["pit_minus_bat"] = X["std_success"] - X["bat_std_success"]
    X["pit_minus_bat_mid"] = X["std_middle"] - X["bat_std_middle"]

    if columns is not None:
        missing = [c for c in columns if c not in X.columns]
        if missing:
            raise ValueError(f"cannot build training features from test data: {missing}")
        X = X[list(columns)]
    return X


DATA_DIR = "./data"
MODEL_PATH = "./model/model.joblib"
OUT_PATH = "./output/submission.csv"


def main():
    t0 = time.time()
    art = joblib.load(MODEL_PATH)
    models, columns, ctx = art["models"], art["columns"], art["ctx"]
    offset = art["logit_offset"]
    print(f"model: {len(models)} trees ensembles, {len(columns)} features, "
          f"logit_offset={offset:+.4f} ({time.time() - t0:.1f}s)", flush=True)

    test = pd.read_csv(os.path.join(DATA_DIR, "test.csv"), encoding="utf-8-sig")
    sub = pd.read_csv(os.path.join(DATA_DIR, "sample_submission.csv"),
                      encoding="utf-8-sig")
    print(f"test={len(test)} submission={len(sub)} ({time.time() - t0:.1f}s)",
          flush=True)

    X = build_features(test, ctx, columns)
    p = np.mean([m.predict_proba(X)[:, 1] for m in models], axis=0)

    # season drift: one constant in logit space, identical for every row
    z = np.log(np.clip(p, EPS, 1 - EPS) / (1 - np.clip(p, EPS, 1 - EPS))) + offset
    p = np.clip(1.0 / (1.0 + np.exp(-z)), EPS, 1 - EPS)
    print(f"predicted mean={p.mean():.4f} min={p.min():.4f} max={p.max():.4f} "
          f"({time.time() - t0:.1f}s)", flush=True)

    pred = pd.Series(p, index=test[ID_COL].to_numpy())
    out = pd.DataFrame({ID_COL: sub[ID_COL]})
    out[TARGET_COL] = out[ID_COL].map(pred)
    missing = int(out[TARGET_COL].isna().sum())
    if missing:
        print(f"warning: {missing} row_id(s) had no prediction -> filled with "
              f"the forecast rate", flush=True)
        out[TARGET_COL] = out[TARGET_COL].fillna(art["target_rate"])

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    out.to_csv(OUT_PATH, index=False, encoding="utf-8")
    print(f"wrote {OUT_PATH} rows={len(out)} (total {time.time() - t0:.1f}s)",
          flush=True)


if __name__ == "__main__":
    main()
